paths:
    directory: NBA
    database: db_path
    graphs: graph_path
    settings: settings path

prediction:
    predict_lines: False

models:
    four_factor_regression:
        options:
            graph: False
            console_out: False

league_year: 2019
