paths:
    directory: NBA
    database: db_path
    graphs: graph_path
    settings: settings path

Bovada:
    regularURL: https://www.bovada.lv/services/sports/event/v2/events/A/description/basketball/nba
    playoffURL: https://www.bovada.lv/services/sports/event/v2/events/A/description/basketball/nba-playoffs

prediction:
    predict_lines: False

models:
    four_factor_regression:
        options:
            graph: False
            console_out: False

league_year: 2019
