paths:
    directory: NBA
    database: db_path
    graph_dir: graph_path
    settings: settings path

Bovada:
    regularURL: https://www.bovada.lv/services/sports/event/v2/events/A/description/basketball/nba
    playoffURL: https://www.bovada.lv/services/sports/event/v2/events/A/description/basketball/nba-playoffs

prediction:
    predict_lines: False

models:
    four_factor_regression:
        options:
            graph: True
            console_out: True
    Bayesian_model:
        settings:
    ML_model:
        settings:

league_year: 2020
